# Generated by Django 3.2.5 on 2021-07-10 12:59

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to=file.models.upload_path)),
                ('title', models.CharField(max_length=32)),
            ],
        ),
    ]
