# Generated by Django 3.2.5 on 2021-07-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_bussiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='title',
        ),
    ]
