# Generated by Django 3.2.5 on 2021-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_remove_files_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
