# Generated by Django 3.2.5 on 2021-07-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('industry', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('zip', models.CharField(blank=True, max_length=300, null=True)),
                ('county', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('fax', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('contact', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.CharField(blank=True, max_length=300, null=True)),
                ('employee', models.CharField(blank=True, max_length=300, null=True)),
                ('sales', models.CharField(blank=True, max_length=300, null=True)),
                ('range', models.CharField(blank=True, max_length=300, null=True)),
                ('sic', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('latitude', models.CharField(blank=True, max_length=300, null=True)),
                ('longitude', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
